name: Java CI with Maven and Selenium

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o código do repositório
        uses: actions/checkout@v4

      - name: Configurar o Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Instalar o Google Chrome e WebDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Executar os Testes Automatizados
        run: mvn clean test -DargLine="-Djava.awt.headless=true"


      - name: Salvar Evidências de Teste (Prints)
        if: always() # Garante que vai salvar os prints mesmo se algum teste der erro!
        uses: actions/upload-artifact@v4
        with:
          name: evidencias-dos-testes
          path: evidencias/
          retention-days: 5 # Guarda os arquivos por 5 dias antes de apagar automaticamente